version: 2.1
orbs:
  node: circleci/node@2.0.1

jobs:
  test:
    executor:
      name: node/default
      tag: '13.12.0'
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: yarn test
      - run:
          name: Run Lint
          command: yarn lint
  deploy:
    executor:
      name: node/default
      tag: '13.12.0'
    steps:
      - checkout
      - run:
          name: Build, authenticate, and publish package
          command: |
            yarn build
            echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/pkg/.npmrc
            yarn npm publish
  deployDocs:
    executor:
      name: node/default
      tag: '13.12.0'
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run: sh ./deploy.sh

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deployDocs:
          filters:
            branches:
              only: master
