name: CI

on:  
  push:
    tags:
      - 'v.*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Execute tests
        run: yarn test
        
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Build, authenticate, and publish package
        run: |
          yarn build
          yarn config set npmAuthToken ${{secrets.NPM_TOKEN}}
          yarn npm publish
            
